-- AlterTable
ALTER TABLE "Order" ADD COLUMN     "is_deleted" BOOLEAN NOT NULL DEFAULT false,
ALTER COLUMN "discount" SET DEFAULT 0,
ALTER COLUMN "total" SET DEFAULT 0,
ALTER COLUMN "date" SET DEFAULT CURRENT_TIMESTAMP;
